print("   ___________")
print(" <|___________|")
print("  |           |__")
print("  |           |  |")
print("  |           |  |")
print("  |           |__|")
print("  |           |")
print("  |           |")
print("  \___________/")  