<<<<<<< HEAD
print("   ___________")
print(" <|___________|")
print("  |           |__")
print("  |           |  |")
print("  |           |  |")
print("  |           |__|")
print("  |           |")
print("  |           |")
=======
print("   ___________")
print(" <|___________|")
print("  |           |__")
print("  |           |  |")
print("  |           |  |")
print("  |           |__|")
print("  |           |")
print("  |           |")
>>>>>>> 45cc1ded8838115dacd16d20aa506ab9607d4717
print("  \___________/")  